### ISSUE TITLE
Can't scroll plugin window on a Mac

### ISSUE THREAD

**Issue by mirkosantangelo** [patrickmatte/scroll-capture#41]
The scrolling function within the plugin window on a Mac isn't working. When attempting to scroll within the plugin window, the browser/site scroll is detected instead, causing the site to scroll down, but not the UI of the extension.

Browser: ARC
OS: Ventura

**Comment by patrickmatte** [comment]
Try the extension on a different website, the etension panel scrolls just fine. But some websites use javascript in ways that can mess with the scroll event, for example they might be calling scrollevent.preventDefault() for some reason and the scroll event will never reach the extension. Since the extension panel is added to the body of the website, the code of the website affects the extension panel. But there should be a small scrollbar that you can use to scroll the extension panel, it is not ideal but better than no scroll at all. But this only happens on a minority of websites that mess with the scroll event.

**Comment by patrickmatte** [comment]
if you can provide a url, I can take a look and investigate a bit more.
